kind: Namespace
apiVersion: v1
metadata:
  name: education
  labels:
    name: education
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: education
spec:
  selector:
    app: nginx-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: education
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx
          image: 'nginx:1.27.3'
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
