
kind: Namespace
apiVersion: v1
metadata:
  name: education
  labels:
    name: education
---
apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer
  namespace: education
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: education
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: kubernetes-bootcamp
          image: 'gcr.io/google-samples/kubernetes-bootcamp:v1'
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
