kind: Namespace
apiVersion: v1
metadata:
  name: education
  labels:
    name: education
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service1
  namespace: education
spec:
  selector:
    app: nginx-app1
  ports:
    - port: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx1
  namespace: education
  labels:
    app: nginx-app1
spec:
  containers:
    - name: nginx1
      image: 'nginx:1.27.3'
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service2
  namespace: education
spec:
  selector:
    app: nginx-app2
  ports:
    - port: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx2
  namespace: education
  labels:
    app: nginx-app2
spec:
  containers:
    - name: nginx2
      image: 'nginx:1.27.3'
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: node-port1
  namespace: education
spec:
  type: NodePort
  ports:
    - port: 80          # Port exposed within the cluster
      targetPort: 80    # Port on the pods
      nodePort: 30001   # Port accessible externally on each node
  selector:
    app: nginx-app1     # Select pods with this label
---
kind: Service
apiVersion: v1
metadata:
  name: node-port2
  namespace: education
spec:
  type: NodePort
  ports:
    - port: 80          # Port exposed within the cluster
      targetPort: 80    # Port on the pods
      nodePort: 30002   # Port accessible externally on each node
  selector:
    app: nginx-app2     # Select pods with this label
